<div class="box simple_contact">
 
<form id="fixit_send_your_phone_form" name="fixit_send_your_phone_form" action="<?php echo $this->getUrl('send-your-phone/') ?>index/sendemail" method="post">

<div class='gf_browser_chrome gform_wrapper' id='gform_wrapper_2' >
	<a id='gf_2' name='gf_2' class='gform_anchor' ></a>

		<div class='gform_body'>
			<ul id='gform_fields_2' class='gform_fields top_label description_below'>
				<li id='field_2_1' class='gfield               gfield_contains_required' >
				<label class='gfield_label' for='input_2_1_3'>Naam
					<span class='gfield_required'>*
					</span>
				</label>
				<div class='ginput_complex ginput_container' id='input_2_1'>
					<span id='input_2_1_3_container' class='ginput_left'>
						<input type='text' name='firstname' id='input_2_1_3' value='' tabindex='1' />
						<label for='input_2_1_3'>Voornaam
						</label>
					</span>
					<span id='input_2_1_6_container' class='ginput_right'>
						<input type='text' name='surname' id='input_2_1_6' value='' tabindex='2' />
						<label for='input_2_1_6'>Achternaam
						</label>
					</span>
					<div class='gf_clear gf_clear_complex'>
					</div>
				</div>
				</li>
				<li id='field_2_2' class='gfield' >
				<label class='gfield_label' for='input_2_2_1'>Adres
				</label>
				<div class='ginput_complex ginput_container' id='input_2_2'>
					<span class='ginput_full' id='input_2_2_1_container'>
						<input type='text' name='street' id='input_2_2_1' value='' tabindex='3' />
						<label for='input_2_2_1' id='input_2_2_1_label'>Straat + huisnummer
						</label>
					</span>
					<span class='ginput_left' id='input_2_2_3_container'>
						<input type='text' name='zip' id='input_2_2_3' value='' tabindex='4' />
						<label for='input_2_2_3' id='input_2_2.3_label'>Postcode
						</label>
					</span>
					<input type='hidden' class='gform_hidden' name='input_2.4' id='input_2_2_4' value=''/>
					<span class='ginput_right' id='input_2_2_5_container'>
						<input type='text' name='city' id='input_2_2_5' value='' tabindex='5' />
						<label for='input_2_2_5' id='input_2_2_5_label'>Plaats
						</label>
					</span>
					<input type='hidden' class='gform_hidden' name='input_2.6' id='input_2_2_6' value=''/>
					<div class='gf_clear gf_clear_complex'>
					</div>
				</div>
				</li>
				<li id='field_2_3' class='gfield               gfield_contains_required' >
				<label class='gfield_label' for='input_2_3'>Telefoon
					<span class='gfield_required'>*
					</span>
				</label>
				<div class='ginput_container'>
					<input name='phone' id='input_2_3' type='text' value='' class='medium' tabindex='6'  />
				</div>
				</li>
				<li id='field_2_4' class='gfield               gfield_contains_required' >
				<label class='gfield_label' for='input_2_4'>E-mailadres
					<span class='gfield_required'>*
					</span>
				</label>
				<div class='ginput_container'>
					<input name='email' id='input_2_4' type='text' value='' class='medium'  tabindex='7'   />
				</div>
				</li>
				<li id='field_2_5' class='gfield               gfield_contains_required' >
				<label class='gfield_label' for='input_2_5'>Merk + type
					<span class='gfield_required'>*
					</span>
				</label>
				<div class='ginput_container'>
					<input name='brand' id='input_2_5' type='text' value='' class='medium'  tabindex='8'   />
				</div>
				</li>
				<li id='field_2_7' class='gfield' >
				<label class='gfield_label' for='input_2_7'>IMEI-nummer/Serienummer(optioneel)
				</label>
				<div class='ginput_container'>
					<input name='imei' id='input_2_7' type='text' value='' class='medium'  tabindex='9'   />
				</div>
				</li>
				<li id='field_2_9' class='gfield' >
				<label class='gfield_label' for='input_2_9'>Pincode (voor het behouden van uw data)
				</label>
				<div class='ginput_container'>
					<input name='pincode' id='input_2_9' type='text' value='' class='medium'  tabindex='10'   />
				</div>
				</li>
				<li id='field_2_8' class='gfield               gfield_contains_required' >
				<label class='gfield_label' for='input_2_8'>Klacht
					<span class='gfield_required'>*
					</span>
				</label>
				<div class='ginput_container'>
					<textarea name='message' id='input_2_8' class='textarea medium' tabindex='11'   rows='10' cols='50'>
					</textarea>
				</div>
				</li>
<input type="submit" name="submit" value="Versturen" />
			</ul>
		</div>

</div>


</form>


</div>
